### PR TITLE
Change sdk compile version to 28

### PR DESCRIPTION
**Pull request by phsacramento**
In order to avoid compatibility issues i have changed compiler version to 28.

### CODE REVIEW

**Comment by Danesz** [comment]
Thanks!

**Comment by hbcysiv** [comment]
https://pub.dev/packages/store_redirect is still at 1.0.1. 
Could you please release so that one can take advantage of this change

**Comment by harmeetbedi** [comment]
https://pub.dev/packages/store_redirect is still at 1.0.1. Can you release this fix please.

**Comment by Danesz** [comment]
Done.

**Pull request merged**
