### PR TITLE
Fix ios

### PR DESCRIPTION
**Pull request by AurelVU**
Fixed a bug on new versions of iOS, due to which the link did not open (old method is deprecated https://developer.apple.com/documentation/uikit/uiapplication/1622961-openurl)

### CODE REVIEW

**Comment by Danesz** [comment]
Hi @AurelVU , thank you for the fix!

Could you please resolve the merge conflicts (you can re-introduce those removed files), and do an iOS version check as part of the fix? (if 10+, use the new API, else the old one)

Thank you!

**Comment by AurelVU** [comment]
Your order has been completed!

**Comment by Danesz** [comment]
Thank you!

**Comment by AurelVU** [comment]
Please tell me when to expect a library update on pub.dev?

**Comment by Danesz** [comment]
Thank you, 2.0.3 is released 🎉

**Pull request merged**
