### PR TITLE
Bump the compileSdk version to 34

### PR DESCRIPTION
**Pull request by rvermaSurecost**
The flutter sdk v3.24.1 is causing issue while generating android release build. So, upgrade of complieSdk to 34 worked

### CODE REVIEW

**Review by mainul-atlasprimer — APPROVED** [review]

**Comment by sourav-xarterian** [comment]
Please Merge this PR. I really need to ship my update which is getting blocked because of this.

**Comment by fcjaramillo** [comment]
@sourav-xarterian 
My recommendation while accepting this change is that you change your pubspec by

```
store_redirect:
    git:
      url: https://github.com/rvermaSurecost/store_redirect.git
      ref: bump-compilesdk-to-34
```

this way you download the change

**Comment by sourav-xarterian** [comment]
Thank you so much, @fcjaramillo!

**Comment by Danesz** [comment]
Hi @rvermaSurecost , thank you for the PR!

Could you please clean up the code and only leave there the necessary changes?
(I guess you only need verison bumps and the rest of the changes can be reverted?)

**Comment by rvermaSurecost** [comment]
Changes done. Now that looks fine

**Comment by Danesz** [comment]
Thank you, 2.0.3 is released 🎉

**Pull request merged**
